### ISSUE TITLE
CRUD operations

### ISSUE THREAD

**Issue by IonicaBizau** [fortunejs/fortune#156]
I just discovered this project, and looks cool, but as beginner I have no idea how to run the crud operations.

I need to `create`, `read` (I guess using the `find` method), `update` and `delete` things.

I tried to do:

```js
// store.js
const fortune = require('fortune')
    , nedbAdapter = require('fortune-nedb')
    ;

var f = fortune({
  adapter: {
    type: nedbAdapter,
    options: {
        dbPath: "foo.json"
    }
  }
}).defineType('user', {
    name: {
        type: String
    }
}).defineType('post', {
    message: {
        type: String
    },

    // One-to-many relationship of post author to user posts.
    author: {
        link: 'user',
        inverse: 'posts'
    }
});

f.adapter.create("user", {
    name: "Alice"
}).then(function (data) {
    console.log(data);
}, function (err) {
    console.log(err);
});
```

But I'm getting:

```
[TypeError: Cannot read property 'user' of undefined]
```

What am I doing wrong?

**Comment by 0x8890** [comment]
You need to call the `connect` method before you can do anything. The constructor can't call `connect` automatically, because it can't know when setup is done.

Maybe this is the wrong approach, and the constructor itself should handle all of the setup, actually it doesn't even make sense to be able to redefine types and transform functions on the fly. In version 2, it will likely fix this and make the setup less confusing and more declarative.

**Comment by IonicaBizau** [comment]
Thanks for quick reply, @0x8890! :sparkles: 

I'm posting the working code, just for posterity:

```js
// store.js
const fortune = require('fortune')
    , nedbAdapter = require('fortune-nedb')
    ;

var f = fortune({
  adapter: {
    type: nedbAdapter,
    options: {
        dbPath: "content"
      , autoload: true
    }
  }
}).defineType('user', {
    name: {
        type: String
    },
    posts: { link: 'post', inverse: 'author', isArray: true }
}).defineType('post', {
    message: {
        type: String
    },
    author: {
        link: 'user',
        inverse: 'posts'
    }
});

f.connect().then(function (data) {
    f.adapter.create("user", [{
        name: "Alice"
    }]).then(function (data) {
        console.log(data);
    }).catch(function (err) {
        console.log(err);
    });
    setInterval(function () {
        f.adapter.find("user").then(function (data) {
            console.log(data);
        }).catch(function (err) {
            console.log(err);
        });
    }, 1000);
}, function (err) {
    console.log(err);
});
```

Calling `connect` makes sense, but it would be handy to automagically call it when we call crud operations.

Where can I find more fortunejs examples and good practices? From the quick look I see that it doesn't have so many examples...

**Comment by 0x8890** [comment]
Nah, instead of *magic* I think a better error message would suffice ("need to call `connect` first")

Here's an entire application in ~800 LOC: https://github.com/0x8890/imagenote (should probably add a link to this in the docs)

AFAIK it's used in a few closed-source projects so I can't point to more examples :(

**Comment by IonicaBizau** [comment]
@0x8890 A friendly error would be cool too! I will most probably use this library in one of my projects. If you like I will add more examples (maybe creating the `examples` directory?).

Thanks!

**Comment by 0x8890** [comment]
I got some ideas from your feedback: https://github.com/fortunejs/fortune/issues/157.
