### ISSUE TITLE
How should the update operation look like?

### ISSUE THREAD

**Issue by IonicaBizau** [fortunejs/fortune#159]
Again, the crud operations are still not clear to me. I pretty much understood how `create` and `find` work but I don't know how the `update` data should look like.

Also, I'm not sure if these operations are related to adapters or `fortune` has a special syntax that is converted by the adapters internally?

Are there docs regarding these crud operations?
Thanks! :apple:

**Comment by 0x8890** [comment]
There are just three update operators that should be implemented as a baseline, because they are used internally: `replace`, `push`, `pull`. All other update operators are specific to an adapter. For example, an update payload may look like:
```js
[{ id: 1, replace: { name: 'Foobar' } }]
```
This will replace the field `name` with the value `Foobar` on the record with ID `1`.

This is documented here: http://fortunejs.com/api/#adapter-update

**Comment by IonicaBizau** [comment]
@0x8890 Oh, I see! Thanks! :cake:
