### ISSUE TITLE
Some examples to understand API

### ISSUE THREAD

**Issue by vabatta** [fortunejs/fortune#189]
Hi,

would be really useful to get some examples to understand how to actually use the API. Most of it it's just written but I couldn't figure out how I really should use it (for example, the validation on schema?).

Thanks and good bye

**Comment by 0x8890** [comment]
For now there's this entire open source application: https://github.com/0x8890/imagenote

It's about 1k lines of code, not too much but also not a small readable example either.

I know examples are lacking :(

**Comment by vabatta** [comment]
I took a look at the example.
I'm looking for the query parameters to sort, range or whatever using the default fortunejs serving (like ?sort=-name but for example, how works range?)

**Comment by 0x8890** [comment]
The ad hoc JSON serializer that it comes with is not documented, currently the only way to see how to use it is the [tests](https://github.com/fortunejs/fortune/blob/master/test/integration/net/json.js), though not everything is tested yet.

I would recommend using the [Micro API](https://github.com/fortunejs/fortune-micro-api) or [JSON API](https://github.com/fortunejs/fortune-json-api) serializer for now. Particularly, the JSON API standard already documents [what queries are allowed](http://jsonapi.org/format/#fetching).

**Comment by vabatta** [comment]
Okay, but for those default there isn't any sort of range support (for examples on a date field, like "every field from this date forward")

**Comment by 0x8890** [comment]
It is [implemented](https://github.com/fortunejs/fortune/blob/81f0889897b1c0d4b5e08125f3b52914bfca81ec/lib/net/http_json_serializer.js#L116-L127), but no test case for it yet. Example:

```
?range[date_field]=1992-03-17&range[date_field]=1994-04-20
```

Another option is to use the wire protocol, which accepts exactly the arguments of the `request` method.

**Comment by 0x8890** [comment]
There is a related issue now https://github.com/fortunejs/fortune/issues/198.

The idea is this:
- First the built-in query parsing needs to be extracted so that it may be reused in any HTTP serializer.
- Then a built-in HTML serializer, that responds to the same exact URIs and queries as the default JSON serializer, provides a human-friendly interface for using and understanding the context and controls of the response. By using content negotiation, one can switch between HTML/JSON seamlessly.
- Since the default JSON serializer is not hypermedia like HTML, I'd recommend using the Micro API serializer for machine-to-machine hypermedia.

I think that having a human interface that is compatible with the machine interface would be more useful than documentation, but still docs are nice.

**Comment by 0x8890** [comment]
So now the HTML serializer is done. You can start up a server:

```
'use strict'

const instance = require('fortune/test/integration/test_instance')
const http = require('http')
const fortune = require('fortune')

instance().then(x => http.createServer(fortune.net.http(x)).listen(1337))
```

Point your browser to `http://localhost:1337` and start poking around. Anything you do has a JSON representation! So you could copy and paste from the browser URL and put it into `curl`:

```
curl "http://localhost:1337/user/3?include=friends&include=friends.ownedPets&fields=name&fields=birthday&fields=friends"
```

The same URL is accessible as a web page, or JSON. The Micro API serializer has been updated to use the new default URL/query parser, so you can also get a JSON-LD response back.
