### ISSUE TITLE
Simple JSON output

### ISSUE THREAD

**Issue by maximusmusterus1** [fortunejs/fortune#213]
Hi,

is there an option to simplify the output of the JsonSerializer? Like
`{ "key": "value", … }` for single objects and `[{ … }, { … }, …]` for arrays of objects instead of adding records and count properties?

**Comment by 0x8890** [comment]
There's not a built-in option for that, but you could also extend the default JsonSerializer class to do what you want:

```js
class CustomJsonSerializer extends fortune.net.http.JsonSerializer {
  processResponse (contextResponse) {
    // custom code here...
  }
}
```

This actually simplifies processing the response since it doesn't differentiate between single record and collection so there's no conditional logic or expectation of the payload to be single or not. Also it makes attaching additional information like the total count and included records possible. In short, you could implement it yourself, it's not going to be a configurable option because it hides important information.
