### ISSUE TITLE
Customize status code thrown by transform errors

### ISSUE THREAD

**Issue by bendman** [fortunejs/fortune#222]
When using fortune for HTTP, how could I respond with a particular status code in an error thrown from a transform.

For example, I have validation that a POST request to create a user is supplied with a valid email address.  Right now I have the validation in a transform, but if the validation fails I throw an error which reaches the client as a 500.

How would I throw something more appropriate, like a 400? Does this even belong in a transform?

**Comment by 0x8890** [comment]
Absolutely.

```js
const fortune = require('fortune')
const { errors: { BadRequestError } } = fortune

function input () {
  throw BadRequestError('custom error message!') // HTTP 400 status
}
```

You can inspect what's available in `fortune.errors`. The reasons why typed errors exist is:

- It simplifies how programming errors and intentional errors are handled.
- It decouples the application from the protocol, so errors can be mapped differently for HTTP or WebSocket or whatever.

Of course it is still possible to manually set the response `statusCode` but this I think is less expressive than throwing an error.

**Comment by bendman** [comment]
Okay, I had found the errors themselves on fortune.errors, but I couldn't find docs on which errors throw which status codes for HTTP.  Thanks!

**Comment by 0x8890** [comment]
It's defined here: https://github.com/fortunejs/fortune/blob/821682143d360ac7938b402da69cbc4cce0dc254/lib/net/http_server.js#L33-L46

Currently it's undocumented but the names are corresponding to the status code.
