### ISSUE TITLE
Transition "transform" to "hook"

### ISSUE THREAD

**Issue by 0x8890** [fortunejs/fortune#232]
Right now there is the terminology "transform" function, which is used to describe functions that can be run before a record is written or after a record is read.

I think "hook" is more familiar and does not sound limiting to one use case.

Changes proposed:
- Rename `transforms` to `hooks`, add an alias and deprecation warning.
- Do not require a return value, if a falsy value was returned or resolved then just assume that the existing record or update should be used.

**Comment by dalane** [comment]
Have you thought about adding in additional hooks and/or making these named hooks?

I think it would be really useful if there was a hook for the 'find' method so that there was then an opportunity to inspect and modify the request before it is passed to the adapter.

At the moment, to achieve this I've created a custom adapter and in the find method I inspect the ids and options arguments and make changes depending on certain rules regarding the type requested, etc. Unfortunately with this method I don't have any context regarding the request (i.e has the resource been requested directly or is it an include).

Thoughts?

**Comment by 0x8890** [comment]
I was thinking of sticking with *input* and *output*, and calling them I/O hooks.

Running an input hook for a `find` request would be a breaking change, because it is not anticipated that it would be run, but you're right that it would be very useful. This would be very easy to implement and it would require a major version bump.

**Comment by 0x8890** [comment]
After giving it some thought, I think it's not feasible to do. The problem is that the input hooks always require some input: `create` uses the records to be created, `update` uses the updates, `delete` looks up the records to be deleted in advance. Also conceptually it doesn't make sense because `find` doesn't mutate anything.

An alternative approach would be to monkey-patch the `request` method of the instance, like so:

```js
var originalRequest = store.request
store.request = function (request) {
  if (!request.method || request.method === 'find') {
    // custom logic
  }
  return originalRequest.call(this, request)
}
```

**Comment by dalane** [comment]
I had a look too and played with some ideas on how it might be implemented and it didn't look pretty.

Thanks for the suggestion though. It's simplified my code a lot.

**Comment by kketch** [comment]
@dalane you could subclass your adapter and override its find method, this how i'm doing it currently on a project

**Comment by dalane** [comment]
Thanks @kketch. That was my original approach but I lacked some context about the request once it got to the adapter. For example, I didn't know if the request was for included records, or related records from another record which is why I was looking for an alternative approach.
