### ISSUE TITLE
Input hook for find method

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune#242]
Is there a possibility to add an input hook for the find method ?

-------

I implemented a token based authentication (using express and node-jwt), so before each protected endpoints the token is verified and some decoded information are saved into the request. 

What if I want to display all the devices for a given user ? If the user do a request to `/devices/` he will get all the devices. 
I would like to modify the request on the fly, so when the user do a request on `/devices`, I will use some information stored into the request (from the decoded and verified jwt token) to only get its devices.

**Comment by 0x8890** [comment]
In short, no. There was some discussion about this https://github.com/fortunejs/fortune/issues/232

The JSON API and Micro API serializers do something similar to what you want, they intercept a URL like this:

```
/:type/:id/:relationship
```

and rewrite the request so that the ids and type are the relationship type and ids. so in your example, such a request would look like `GET /users/1/devices`.

if you care about having a short url like `/devices` being rewritten to `/users/1/devices`, feel free to intercept the request before it gets to fortune's http listener:

```js
const fortuneListener = fortune.net.http(store)

http.createServer((request, response) =>
  new Promise((resolve, reject) => {
    if (request.headers['Authorization'])
      return adapter.find(/* your query here */).then(result => {
        request.url = '/rewrite/url/here'
        resolve()
      })

    response.statusCode = 401
    response.end()
    throw fortune.errors.UnauthorizedError()
  })
  .then(() => fortuneListener(request, response)))
```

**Comment by thomasthiebaud** [comment]
Thank you, will see what I can do with it. But I think I will try to avoid rewriting request.
