### ISSUE TITLE
Use an Array as inverse

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune#243]
Hej, 

I have this two models

```
const rule = {
  formula: String,
  inputSignals: [Array('signal'), 'rules'],
  name: String,
  outputSignals: [Array('signal'), 'rules'],
};

const signal = {
  code: String,
  name: String,
  rules: [Array('rule'), ['inputSignals', 'outputSignals']],
  unit: String,
};
```

I get this error

> TypeError: The "inverse" on "rules" must be a string.

Is there a way to use the same inverse for two differents properties ? If not is there another way than created two inverses to do it ?

**Comment by 0x8890** [comment]
Bonjour,

That is not possible, and probably is impossible. Let's look at your example to see why. Suppose we have for *inputSignals* the value `[ 1, 2, 3 ]`, and for *outputSignals* the value `[ 3, 4, 5 ]`. That means that *rules* would be `[ 1, 2, 3, 4, 5 ]`. Now what happens if we remove `3` from *inputSignals*, then *rules* gets updated to `[ 1, 2, 4, 5 ]`, which is wrong, because *outputSignals* still has `3` but it's not in the inverse.

My suggestion is to just define two inverse fields, *inputRules* & *outputRules*. Then *rules* would be the union of *inputRules* and *outputRules*.

**Comment by thomasthiebaud** [comment]
You are right, it make no sense. Thank you for you answer.
