### ISSUE TITLE
Only count the amount of results using find

### ISSUE THREAD

**Issue by Voles** [fortunejs/fortune#256]
I'd like to count the amount of results of a `find` from a rather large dataset. I don't need the result objects, only the count. Is there a way to do this using the `find` method?

**Comment by sapeien** [comment]
One can set the `limit` option to one and it should work with negligible impact. There's not really a built-in way to return nothing but still count records. In virtually every database, setting the limit of a query to zero is the same as no limit.

If returning one record isn't acceptable and you only care about the total count, it might make sense to just use the underlying database driver directly since that would be a rather trivial query.

**Comment by Voles** [comment]
@sapeien that's clear, thanks very much!
