### ISSUE TITLE
setting up fortune as JSON API Client in web browser

### ISSUE THREAD

**Issue by emmanueldaher** [fortunejs/fortune#261]
Hello,
I'm reading everything about FortuneJS, but I'm not shure if it's  possible to run fortune js as client in web browser.

**Comment by sapeien** [comment]
**Global method (window.fortune):***
- The fastest way is to just use the direct link from GitHub pages, which is on the homepage: http://fortune.js.org/fortune.min.js
- There's also a built version in the published package, i.e. https://unpkg.com/fortune@5.1.0/dist/fortune.min.js

**Build tooling:**
- If you're using `npm` you can `require('fortune')` and it should just work with tools like browserify.
- With build tooling you can use the [`fortune-indexeddb`](https://github.com/fortunejs/fortune-indexeddb) package which adds persistence in the browser.

**Comment by emmanueldaher** [comment]
Ok,
After 1 day of researching I was  capable of inject fortune in my web application using [Webpack](https://webpack.js.org/).
But now I'm kind of lost,
I can't find anything about using Fortune as web client on the Docs page.
I need to consume a JSON API, I found [fortune-json-api](https://github.com/fortunejs/fortune-json-api), but no documentation either about client side.

Anyone can help?

**Comment by thibremy** [comment]
Hello @emmanueldaher 

[fortune-json-api](https://github.com/fortunejs/fortune-json-api) is an [HTTP Serializers](http://fortune.js.org/plugins/#http-serializers).

An `adapter` is where you store your data compare to `networking plugins` which focus on `communication`.

[fortune-http](http://fortune.js.org/api/#fortunehttp-createlistener) is a networking plugins which allows to use an [http serializer](http://fortune.js.org/plugins/#http-serializers) to format your data. It's work only on server-side (based  on http.createServer).

If you use ember-data, you don't need fortune.js, take a look at [ember-localstorage-adapter](https://github.com/locks/ember-localstorage-adapter) may be it could help you.

**Comment by sapeien** [comment]
>After 1 day of researching I was capable of inject fortune in my web application using Webpack.

This is why I recommended using either the global version or browserify, there is no configuration needed, hence less things that can go wrong.

>I need to consume a JSON API

You're looking for a HTTP client library, while `fortune-json-api` is intended for servers that need to output JSON API. Seeing `http.createServer` in the usage example should make that pretty obvious.

The most feature complete JSON API client and probably most well supported is Ember Data, there is also Orbit.js if you're not using Ember but I have no experience with it. None of these options have a decent offline experience due to lack of proper IndexedDB support. I did not bother to write a JSON API client because Yehuda Katz invented the media type as the preferred format for Ember Data, so I didn't see the point of competing with that project.

Fortune.js is very focused on just being a database abstraction, with the network as a means of interacting with the database (most production databases talk to applications via a network protocol anyways). It does not try to do everything, and it is outside of the scope of this library to also be a HTTP API client, it just wouldn't make sense (except for those databases that speak HTTP like CouchDB or Neo4j).

**Comment by emmanueldaher** [comment]
@thibremy thank you by the clarification,
I took a look at ember-data, but it relies on EmberJS and I'm using AngularJS.

**Comment by emmanueldaher** [comment]
@sapeien thanks,
I'm gonna take a look at Orbit.js .

I was trying to use Fortune becouse it doesn't rely on any framework, offline suport, defined models and etc, and it seemed to be the most manteined repo of all the implementations listed on the JSON API's website.

I thought it was possible to use the fortune-json-api serializer  with http-fortune, to consume the API, there were many mentions of browser suport in the docs.

**Comment by thibremy** [comment]
Sorry @emmanueldaher I was thinking you use ember-data.

It's only possible to use fortune-json-api with http-fortune, because it's an [http-serializer](http://fortune.js.org/plugins/#http-serializers). Like the documentation said : 
> This section is only relevant to the fortune-http module.

JSON-API is a data format, it's ok when you want to share data across clients but it's overkill to implement it just for `browser` because this layer is not necessary on this use case.

**Comment by sapeien** [comment]
To clarify, the reason why the `fortune-json-api` package does not come with an adapter to consume JSON API, is because I didn't think it was worth duplicating the effort from Ember Data.

Also it is entirely possible to use any generic HTTP client to consume JSON API.

**Comment by kketch** [comment]
@sapeien problem is Ember Data is intended to be used with ember.js, having fortune adapters for JSON API, and maybe fortune-ws seems to be an interesting idea to me.
And Ember data also have many other features related to ember and its observable object pattern which are not expected to be supported by a fortune adapter

**Comment by thibremy** [comment]
@kketch I think it's easiest to do a [custom adapter](http://emberjs.com/api/data/classes/DS.Adapter.html) and  [custom serializer](http://emberjs.com/api/data/classes/DS.Serializer.html) sync with Fortune ws/browser.

From my point of view, I prefer to keep Ember data complexity inside ember's scope.

**Comment by kketch** [comment]
@thibremy I wasn't talking about using fortune with ember data or even ember, but what I meant is that it would be cool to have fortune adapters to query remote data through JSON API per instance or the custom websocket protocol of `fortune-ws`, just like the ones for databases or [fortune-fs](https://github.com/fortunejs/fortune-fs)

**Comment by thibremy** [comment]
@kketch Sorry, I did not understand that, now I see.
But I don't know if we cross the line too much between a data-layer and a sort of 'http client'.
