### ISSUE TITLE
Additional declarative per-resource configuration?

### ISSUE THREAD

**Issue by jmeas** [fortunejs/fortune#276]
Hi there @daliwali :wave:

I'm reading through the guides, and I'm wondering if there's a declarative way to get these features on a per-resource basis:

1. non-nullable fields
2. `createdAt` meta attributes
3. `updatedAt` meta attributes
4. per-resource allowed HTTP methods

From the guides, it seems like the way to do this right now would be imperatively using the input hooks, and keeping all of this logic on the JS side, rather than the DB side. Is that the recommended approach?

Thanks!

**Comment by daliwali** [comment]
I left most of that out intentionally.

1. this is database dependent, if you're using a relational database it should be declared but otherwise not, I left it out since I don't think it should be handled declaratively for all databases.
2, 3. this is trivial to do via the input hook, I don't understand why this needs to be special-cased.
4. the prototype 0.x versions had this, it was later removed after 1.0 since they tended to couple the app to the network protocol, and it was a deliberate decision to keep them as separate as possible.

this is a good idea to add this to the docs.

**Comment by daliwali** [comment]
The motivation is to keep it as a general purpose library without assuming any specific use cases. Trying to anticipate specific use cases is always going to lead to bloat and unnecessary API. I am optimistic that programmers can figure out things on their own.

For example, the last point could be handled entirely on the application side:

```js
var originalRequest = store.request

store.request = function (options) {
  var type = options.type
  var method = options.method

  if (method === 'delete' && type === 'payment')
    return Promise.reject(new BadRequestError('Payments may not be deleted.'))

  return originalRequest.call(this, options)
}
```

**Comment by jmeas** [comment]
Thanks @daliwali ! All of this makes sense.

I'm going to close this issue out, and I'll be sure to add these common use cases to the examples I'll be working on shortly.
