### ISSUE TITLE
Question about joining models

### ISSUE THREAD

**Issue by jjcm** [fortunejs/fortune#277]
Hey guys, I'm trying to do a simple join using the include syntax, but I'm not getting anything from it. Curious what I'm doing wrong. The call I'm making is:

```
store.find('postTag', null, {}, [['post']]).then(results => {
  console.log(results.payload)
})
```

Currently my data model is

```
const store = fortune(
  {
    post: {
      title: String,
      OC: Boolean,
      url: String,
      user: 'user',
      thumbnail: String,
      score: Number,
      grade: Number,
      date: Date,
      content: String,
      type: String,
      tags: Array('postTag')
    },
    postTag: {
      tag: 'tag',
      post: 'post',
      upvotes: Number,
      downvotes: Number,
      date: Date
    },
...
```

I'm expecting the returned set of postTags to include the relevent post data inside of them, but instead I'm just getting the post id: 
`{"tag":"YPGpbTqv9aeZHXxBNgIC","post":"b/sbbIZpDDXLnZcIkYng","upvotes":259,"downvotes":null,"date":"2017-04-25T15:06:08.475Z","id":"l4FmJVzWBUEnQWcP9fpv"}`

Am I doing this join correctly? If not, how do I need to modify the include so the post data is included in the postTag object.

**Comment by jjcm** [comment]
Ah, just noticed fortune appends it in the include key at the end. Nevermind all :)

**Comment by jjcm** [comment]
Actually before I drop out - is there a way to make fortune merge this data rather than returning it as two separate arrays of objects?

**Comment by daliwali** [comment]
@jjcm the arrays are intentional. Hypothetically, let's say you're fetching 100 posts and you want to include tags, and most of the tags overlap. Embedding tags in each post would repeat the same information many times, and the problem is compounded if you want to include more than one level. This is the approach that many formats have taken, it is highly inefficient, short-term optimized thinking in practice.

Fortune.js internally does a modified Breadth-First Search (BFS) when fetching includes, ignoring records that it has already seen. It's optimized to reduce database requests and bandwidth over the network. If you want to de-optimize this, it's up to you.

**Comment by jjcm** [comment]
Yep, totally get that approach for one-to-many relationships. Just wanted to make sure that there weren't fortune-based ways to merge in the case of many-to-many relationships scoped to a unique tag or post, resulting in non-duplicates of the other side. Closing this for now, thanks for the answer man.
