### ISSUE TITLE
Does fortunejs work with AWS Lambda? 

### ISSUE THREAD

**Issue by deanmraz** [fortunejs/fortune#288]
Hi all, Couldn't find any documentation on the use with AWS Lambda, so thought I would ask it here. If this is not the appropriate place to ask, please direct me and I'll be happy to close this. Thanks!

**Comment by daliwali** [comment]
Using only the `fortune` package should work anywhere JS can run.

However `fortune-http` won't work out of the box. That is because AWS has their own proprietary API signature, and doesn't support the core HTTP module from Node.js.

I'm not interested in supporting AWS Lambda, a commercial platform, for free.

**Comment by deanmraz** [comment]
@daliwali thanks for the response. Would the JSON API serializer work without fortune-http?

**Comment by daliwali** [comment]
no, it also relies on Node.js HTTP.

one would need to map the Node.js HTTP API to Lambda, which could be an open source project on its own.

**Comment by deanmraz** [comment]
@daliwali ya, thats what I thought. Maybe I can look into this https://github.com/awslabs/aws-serverless-express. 

Thanks for the feedback!
