### ISSUE TITLE
Delete and Update request results for use with adapters

### ISSUE THREAD

**Issue by CTOJoe** [fortunejs/fortune#289]
When a Fortune update or delete request is made, an adapter find request is performed for validation. Is there a reason the resulting records are not passed to the adapter update and delete methods? If a custom adapter is written where the records results are required for manipulation on the datastore, it would be redundant to run the same find request again.

**Comment by daliwali** [comment]
@CTOJoe yes, there are good reasons.

- The initial `find` request is made so that application logic can be performed, there is no way around this other than assuming that the record won't be read before updates (which is not a useful assumption).
- Only the `update` object is passed to the adapter and not the full record, because records may be updated partially, or only atomic operators may be involved such as push/pull to array. Not writing entire records improves write performance dramatically, especially with lots of fields.
- Fortune.js does not actually *need* meaningful results from `update` or `delete`, because it applies updates to objects in memory after a successful update, eliminating an unnecessary round-trip to the database.

I hope that answers your question.

**Comment by CTOJoe** [comment]
Firstly, thanks for getting back to me so quickly. I understand the reasoning for the initial `find` request. I know that `update` and `delete` will not return anything meaningful, and I am not asking for this.

The resulting records of the initial compulsory `find` request are not being passed to the subsequent _adapter_ `update` and `delete` methods.  It would be helpful if the _adapter_ [update](http://fortune.js.org/api/#adapter-update) and [delete](http://fortune.js.org/api/#adapter-delete) methods received the resulting records of the compulsory `find` method as arguments to be used by the adapter.

Specifically I am writing an adapter for Google Cloud Spanner.  The Spanner client has specific requirements due to "interleaving" and is its id keys, requiring record data for record manipulation.

I am open to writing a PR, but I'm not sure how you'd like to implement it or whether this functionality was intentionally left out (links to lines where records are not passed to adapter below).

[Delete Reference](https://github.com/fortunejs/fortune/blob/15d8ec7e6a012c154d69c60088e1cee5d1c3398a/lib/dispatch/delete.js#L74)

[Update Reference](https://github.com/fortunejs/fortune/blob/15d8ec7e6a012c154d69c60088e1cee5d1c3398a/lib/dispatch/update.js#L168)

**Comment by daliwali** [comment]
My recommendation is that the records returned from the initial `find` should be on `meta`:

```js
context.request.meta.records = records
```

This way, it gets passed to the adapter, which can optionally make use of it. Right now `meta` is empty by default. I would be open to including useful info by default.

**Comment by bpinney** [comment]
Your suggestion seems to be workable and fairly easy to implement, but we're concerned that polluting the `meta` object with results of `find` may take away from what users can to do with `meta`. There would be a reserved key in the `meta` object, creating limitations and documentation requirements. We thought passing the results as an argument to `update`/`delete` would be the cleanest way of solving the problem: 

`Adapter.delete(type, [ids], [meta], [records]) => Promise`
`Adapter.update(type, updates, [meta], [records]) => Promise`

We think if it is added as the last argument this would not cause backwards compatability issues while not polluting the `meta` object.

Let me know what you think, and if we should implement this in a PR.

**Comment by daliwali** [comment]
I don't think it's a limitation or creates much documentation. I can't really think of why it would be a bad thing to introduce default fields on meta. To avoid key conflicts, I would suggest using symbols: `meta[keys.findRecords]`, where `findRecords` refers to a symbol.

Basically I don't want to introduce a new argument for every new use case, `meta` is supposed to be a catch-all object.

**Comment by bpinney** [comment]
That makes sense if `meta` is intended as a catch-all object. Would you like to do this yourself or have us provide a PR adding the symbol constant [here](https://github.com/fortunejs/fortune/blob/15d8ec7e6a012c154d69c60088e1cee5d1c3398a/lib/common/constants.js#L24)?

**Comment by daliwali** [comment]
I would appreciate a PR! Here's what I think should be done:

- Add a new symbol by adding it [here](https://github.com/fortunejs/fortune/blob/15d8ec7e6a012c154d69c60088e1cee5d1c3398a/lib/common/constants.js#L5).
- Assign it on `meta` when updating/deleting.
- Add a note about it [here](https://github.com/fortunejs/fortune/blob/15d8ec7e6a012c154d69c60088e1cee5d1c3398a/lib/index.js#L346).

**Comment by daliwali** [comment]
Released as `5.4.0` https://github.com/fortunejs/fortune/commit/93bd5d9d1286b4839520a7e2aba26f7f01ac553d

**Comment by bpinney** [comment]
After further analysis we have concluded that this may not be the concern of fortune, rather that of an adapter. We found a better way to do this at the adapter level which does not require `findRecords` in the `meta` object at all. We think this "feature" and our subsequent PR implementing it should be removed altogether.

Our reasoning: 
1. Not every adapter will use this.
2. No known adapters use this today.
3. We are concerned that in the future, manipulation of the reference `findRecords` may change the object unintentionally, requiring cloning/dereferencing to maintain integrity of the object.
4. Potential for increased memory overhead.
5. Removing `findRecords` from the `meta` object will clean the object of an unnecessary symbol.
6. An adapter can store the records/information it requires in `meta` independently because fortune invokes the adapter's own `find` method directly.

Would you like to revert this change, or keep it anyway? If you keep it, we found a bug with it when chaining method calls which subsequently call `find` and have a PR prepared to fix it. Not every day you get someone asking to remove their PR, but we would like to maintain the integrity of this project. Thoughts?

**Comment by CTOJoe** [comment]
![Mega face palm](https://i.kinja-img.com/gawker-media/image/upload/s--YYpNn9Rb--/c_scale,f_auto,fl_progressive,q_80,w_800/smewr4cle6fjjisumhsf.gif)

**Comment by daliwali** [comment]
>we found a bug with it when chaining method calls which subsequently call find and have a PR prepared to fix it.

That is particularly nasty! I would be in favor of removing it for this reason alone.

**Comment by bpinney** [comment]
How should we proceed?

**Comment by daliwali** [comment]
I'll handle removing it -- nothing needed from your side, thanks!

**Comment by daliwali** [comment]
Done https://github.com/fortunejs/fortune/commit/57da6a49a6e2dc76b81b4351912b3cd3bcfc9083

New version has been published.
