### ISSUE TITLE
External/Remote Resources

### ISSUE THREAD

**Issue by rhettl** [fortunejs/fortune#296]
Hello, 

I'm musing at refactoring some of my servers to smaller services -- one of which is an email server. I would like to take the email components out of my other servers and combine them. 

On many of my servers, the `User` resources has an `emails: [Array('email'), 'user']` property. If I extract the `Email` resources into its own server, how do I maintain this relationship? 

I figure that the `User` will know about the `Emails`, but the `Emails` don't need to know about the `User`

Thank you for any help you might provide 😄

**Comment by daliwali** [comment]
This is a hard problem because you're asking to maintain a bidirectional relationship on different servers and assuming you have the permission to do it, and that the remote server is going to sync data back.

I would suggest just having a plain string to identify the resource on the remote server, probably a URL. That's how the web at large works.

**Comment by rhettl** [comment]
Thank you
