### ISSUE TITLE
limit does not seam to work

### ISSUE THREAD

**Issue by checkerap** [fortunejs/fortune#306]
I tried ?limit and ?offset, but it does not seam to work.

**Comment by daliwali** [comment]
This is a poorly written issue, and factually incorrect. There are tests for limit and offset.

Internal test: https://github.com/fortunejs/fortune/blob/b02603ccb3e63d2860b361f36d9d4e8af54a8aa6/test/unit/adapter.js#L344-L354
HTTP test: https://github.com/fortunejs/fortune-http/blob/c0dd4fa04ca60b1048eb269c96dbb503ad4f3489/test/json.js#L118-L131

Each adapter runs the internal test as well. This is most likely due to user error.
