### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by ninjatronic** [fortunejs/fortune#81]
I'm eager to see this project hit 1.0. So eager, in fact, I'd like to make some substantial contributions.

Do you have a contributing guide, or a roadmap? Some simple documentation on how to get started contributing and the architecture would be useful.

Thanks

**Comment by daliwali** [comment]
There's the [website page](http://fortunejs.com/contributing/) which will likely be expanded upon.

Also there's some rudimentary docs that aren't on the website:
https://github.com/fortunejs/fortune/tree/master/lib
https://github.com/fortunejs/fortune/blob/master/doc/TODO.md

One of the big blockers to 1.0 right now is the transaction implementation, and in order to do that, an adapter for a database that supports transactions (PostgreSQL) has to be done.

**Comment by 0x8890** [comment]
Since it's past 1.0 now, closing this.
