### ISSUE TITLE
Generated @hrefs

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#84]
Hey, I'm new to the concepts of [micro-api]() though they look very attractive to me. I have few questions:

- Is it by design that hrefs are generated hashes instead of human-readable resource names:

```json
"@links": {
      "user": {
          "@href": "/dXNlcnM"
      }
 }
```
- I'm using mongodb-adapter. Is there some doc where I can check all possible schema fields or is it just `type`? What about unique fields and mongo indexes etc.? As I understand all fields in `defineType` are required by default on POST/PUT?

- Is there built-in logger?

Thanks!

**Comment by 0x8890** [comment]
It's by design that the Micro API serializer emits URIs that are opaque. The purpose is to prevent hard-coded client URIs, or to extract any information from the URI. This is in line with the [opacity axiom](http://www.w3.org/DesignIssues/Axioms.html#opaque) of URIs. 

With regards to the MongoDB adapter, there's not yet support for unique fields and indexes yet, but such a feature would be easy to add. It's the intention that each adapter will implement the base adapter class, and have extensions that are specific to the data store. MongoDB supports many other data types beyond just the few types that are required by Fortune to implement, it's also just a matter of extending the adapter. How it would be done is by using a `Symbol` as the type.

There's no built-in logger, but the `dispatch` and `http` functions return promises. For example, I could have an http server like so:

```js
import fortune from 'fortune'
import http from 'http'

const store = fortune.create()
const listener = fortune.net.http(store)
const server = http.createServer(function () {
  listener(...arguments)
  .then(response => /* log successful response */)
  .catch(response => /* log error response */)
})

store.connect().then(() => server.listen(1337))
```

**Comment by voronianski** [comment]
@0x8890 thanks, your answers are helpful! I will give it a try and probably come up with additional questions if they'll appear.

**Comment by voronianski** [comment]
@0x8890 for example news ones :)

- I would like to have POST method to some `/resource` but with some payload data I need to go to third-party API, is `app.transform` the right place to make such requests?
- Is there a way to versionify API? I would like to be the root endpoint `/v1`.

**Comment by 0x8890** [comment]
- Yes, to be more precise, `transformInput`.
- Fortune is agnostic about API versioning, although it is [highly advisable that you do not do so](https://twitter.com/fielding/status/376835835670167552). 

If you really wanted to have a `/v1` route, here's how you could do it with express:

```js
import express from 'express'
import fortune from 'fortune'

const app = express()
const store = fortune.create({
  serializers: [ {
    type: fortune.serializers.microApi,
    options: {
      prefix: '/v1'
    }
  } ]
})
const listener = fortune.net.http(store)

app.use('/v1', (request, response, next) =>
  listener(request, response).then(next, next))

app.listen(1337)
```

**Comment by voronianski** [comment]
@0x8890 nice, I was also thinking about possibility mixing fortune with express, your example looks clear :+1:
